/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	F:/SVN_ELF2_SOC/trunk/Basic_Demo/FLASH_Demo/FPGA144/al_ip/AL_MCU.v
 ** Date	:	2018 08 27
 ** TD version	:	4.2.511
\************************************************************/

`timescale 1ns / 1ps

module AL_MCU ( ppm_clk,
	qspi_rxd,
	qspi_txd,
	qspi_sclk,
	qspi_ss,
	qspi_oen,
	gpio_h0_out,
	gpio_h0_oe_n,
	gpio_h0_in );

	input	[3:0]	qspi_rxd;
	output	[3:0]	qspi_txd;
	output	qspi_sclk;
	output	qspi_ss;
	output	[3:0]	qspi_oen;
	input	ppm_clk;
	output	gpio_h0_out;
	output	gpio_h0_oe_n;
	input	gpio_h0_in;
	EF2_PHY_MCU #(
		.GPIO_L0("ENABLE"),
		.GPIO_L1("ENABLE"),
		.GPIO_L7("ENABLE"))
	mcu_inst(
		.ppm_clk(ppm_clk),
		.qspi_rxd(qspi_rxd),
		.qspi_txd(qspi_txd),
		.qspi_sclk(qspi_sclk),
		.qspi_ss(qspi_ss),
		.qspi_oen(qspi_oen),
		.gpio_h_out({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,gpio_h0_out}),
		.gpio_h_oe_n({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,gpio_h0_oe_n}),
		.gpio_h_in({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,gpio_h0_in}));
endmodule