/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	F:/SVN_ELF2_SOC/trunk/Basic_Demo/AHB_Demo/AHB_FPGA144/al_ip/AL_MCU.v
 ** Date	:	2018 08 23
 ** TD version	:	4.2.285
\************************************************************/

`timescale 1ns / 1ps

module AL_MCU ( ppm_clk,
	h2h_haddr,
	h2h_htrans,
	h2h_hwrite,
	h2h_hsize,
	h2h_hburst,
	h2h_hprot,
	h2h_hwdata,
	h2h_hrdata,
	h2h_hreadyout,
	h2h_hresp,
	h2h_mclk,
	h2h_rstn,
	gpio_h0_out,
	gpio_h0_oe_n,
	gpio_h0_in );

	output	[31:0]	h2h_haddr;
	output	[1:0]	h2h_htrans;
	output	h2h_hwrite;
	output	[2:0]	h2h_hsize;
	output	[2:0]	h2h_hburst;
	output	[3:0]	h2h_hprot;
	output	[31:0]	h2h_hwdata;
	input	[31:0]	h2h_hrdata;
	input	h2h_hreadyout;
	input	[1:0]	h2h_hresp;
	input	h2h_mclk;
	input	h2h_rstn;
	input	ppm_clk;
	output	gpio_h0_out;
	output	gpio_h0_oe_n;
	input	gpio_h0_in;
	EF2_PHY_MCU #(
		.GPIO_L0("ENABLE"),
		.GPIO_L1("ENABLE"),
		.GPIO_L7("ENABLE"))
	mcu_inst(
		.ppm_clk(ppm_clk),
		.h2h_haddr(h2h_haddr),
		.h2h_htrans(h2h_htrans),
		.h2h_hwrite(h2h_hwrite),
		.h2h_hsize(h2h_hsize),
		.h2h_hburst(h2h_hburst),
		.h2h_hprot(h2h_hprot),
		.h2h_hwdata(h2h_hwdata),
		.h2h_hrdata(h2h_hrdata),
		.h2h_hreadyout(h2h_hreadyout),
		.h2h_hresp(h2h_hresp),
		.h2h_mclk(h2h_mclk),
		.h2h_rstn(h2h_rstn),
		.gpio_h_out({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,gpio_h0_out}),
		.gpio_h_oe_n({open,open,open,open,open,open,open,open,open,open,open,open,open,open,open,gpio_h0_oe_n}),
		.gpio_h_in({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,gpio_h0_in}));
endmodule