/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/ELF2_SOC_Shanghai/trunk/Demo/BRAM_Demo/Pin48_FPGA/al_ip/sys_pll.v
 ** Date	:	2018 09 05
 ** TD version	:	4.2.285
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             50.000Mhz
//	Clock multiplication factor: 12
//	Clock division factor:       3
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 200.000MHZ	| 0  DEG     
//		C1        	| 25.000 MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module sys_pll(refclk,
		extlock,
		clk0_out,
		clk1_out);

	input refclk;
	output extlock;
	output clk0_out;
	output clk1_out;

	wire clk0_buf;

	EF2_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	EF2_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.DYNCFG("DISABLE"),
		.FIN("50.000"),
		.FEEDBK_MODE("NORMAL"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("DISABLE"),
		.SYNC_ENABLE("ENABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN(6),
		.ICP_CURRENT(3),
		.KVCO(6),
		.LPF_CAPACITOR(3),
		.LPF_RESISTOR(2),
		.REFCLK_DIV(3),
		.FBCLK_DIV(12),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(5),
		.CLKC0_CPHASE(5),
		.CLKC0_FPHASE(0),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(40),
		.CLKC1_CPHASE(40),
		.CLKC1_FPHASE(0),
		.PU_INTP("DISABLE"),
		.INTPI(3),
		.HIGH_SPEED_EN("ENABLE"),
		.SSC_ENABLE("DISABLE"),
		.SSC_MODE("Down"),
		.SSC_AMP(0.0000),
		.SSC_FREQ_DIV(0),
		.SSC_RNGE(0),
		.FREQ_OFFSET(0.0000),
		.OFFSET_MODE("EXT"),
		.FREQ_OFFSET_INT(0),
		.CLKC0_DUTY(0.5000),
		.CLKC0_DUTY_INT(3),
		.CLKC0_DUTY50("ENABLE"),
		.CLKC1_DUTY(0.5000),
		.CLKC1_DUTY_INT(20),
		.CLKC1_DUTY50("ENABLE")	)
	pll_inst (.refclk(refclk),
		.reset(1'b0),
		.stdby(1'b0),
		.extlock(extlock),
		.psclk(1'b0),
		.psdown(1'b0),
		.psstep(1'b0),
		.psclksel(3'b000),
		.psdone(open),
		.dclk(1'b0),
		.dcs(1'b0),
		.dwe(1'b0),
		.di(8'b00000000),
		.daddr(6'b000000),
		.do({open, open, open, open, open, open, open, open}),
		.fbclk(clk0_out),
		.clkc({open, open, open, open, open, clk1_out, clk0_buf}),
		.ssc_en(1'b0),
		.frac_offset_valid(1'b0),
		.dsm_refclk(1'b0),
		.dsm_rst(1'b0));

endmodule
